// Load All
export const COMMENTS_LOADING_REQUEST = 'COMMENTS_LOADING_REQUEST';
export const COMMENTS_LOADING_SUCCESS = 'COMMENTS_LOADING_SUCCESS';
export const COMMENTS_LOADING_FAILURE = 'COMMENTS_LOADING_FAILURE';

// Upload
export const UPLOAD_COMMENT_REQUEST = 'UPLOAD_COMMENT_REQUEST';
export const UPLOAD_COMMENT_SUCCESS = 'UPLOAD_COMMENT_SUCCESS';
export const UPLOAD_COMMENT_FAILURE = 'UPLOAD_COMMENT_FAILURE';

// Edit
export const EDIT_COMMENT_REQUEST = 'EDIT_COMMENT_REQUEST';
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';
export const EDIT_COMMENT_FAILURE = 'EDIT_COMMENT_FAILURE';

// Delete
export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE';
