// Load All Inqueries
export const INQUERIES_LOADING_REQUEST = 'INQUERIES_LOADING_REQUEST';
export const INQUERIES_LOADING_SUCCESS = 'INQUERIES_LOADING_SUCCESS';
export const INQUERIES_LOADING_FAILURE = 'INQUERIES_LOADING_FAILURE';

// Load Inquery
export const INQUERY_LOADING_REQUEST = 'INQUERY_LOADING_REQUEST';
export const INQUERY_LOADING_SUCCESS = 'INQUERY_LOADING_SUCCESS';
export const INQUERY_LOADING_FAILURE = 'INQUERY_LOADING_FAILURE';

// Inquery Write
export const INQUERY_WRITE_REQUEST = 'INQUERY_WRITE_REQUEST';
export const INQUERY_WRITE_SUCCESS = 'INQUERY_WRITE_SUCCESS';
export const INQUERY_WRITE_FAILURE = 'INQUERY_WRITE_FAILURE';

// Inquery Edit
export const INQUERY_EDIT_REQUEST = 'INQUERY_EDIT_REQUEST';
export const INQUERY_EDIT_SUCCESS = 'INQUERY_EDIT_SUCCESS';
export const INQUERY_EDIT_FAILURE = 'INQUERY_EDIT_FAILURE';

// Inquery Delete
export const INQUERY_DELETE_REQUEST = 'INQUERY_DELETE_REQUEST';
export const INQUERY_DELETE_SUCCESS = 'INQUERY_DELETE_SUCCESS';
export const INQUERY_DELETE_FAILURE = 'INQUERY_DELETE_FAILURE';
