// 시설물 추가
export const ADD_FACILITY_REQUEST = 'ADD_FACILITY_REQUEST';
export const ADD_FACILITY_SUCCESS = 'ADD_FACILITY_SUCCESS';
export const ADD_FACILITY_FAILURE = 'ADD_FACILITY_FAILURE';

// 시설물 변경
export const EDIT_FACILITY_REQUEST = 'EDIT_FACILITY_REQUEST';
export const EDIT_FACILITY_SUCCESS = 'EDIT_FACILITY_SUCCESS';
export const EDIT_FACILITY_FAILURE = 'EDIT_FACILITY_FAILURE';

// 시설물 삭제
export const DELETE_FACILITY_REQUEST = 'DELETE_FACILITY_REQUEST';
export const DELETE_FACILITY_SUCCESS = 'DELETE_FACILITY_SUCCESS';
export const DELETE_FACILITY_FAILURE = 'DELETE_FACILITY_FAILURE';

// 건물 추가
export const ADD_BUILDING_REQUEST = 'ADD_BUILDING_REQUEST';
export const ADD_BUILDING_SUCCESS = 'ADD_BUILDING_SUCCESS';
export const ADD_BUILDING_FAILURE = 'ADD_BUILDING_FAILURE';

// 건물 변경
export const EDIT_BUILDING_REQUEST = 'EDIT_BUILDING_REQUEST';
export const EDIT_BUILDING_SUCCESS = 'EDIT_BUILDING_SUCCESS';
export const EDIT_BUILDING_FAILURE = 'EDIT_BUILDING_FAILURE';

// 건물 삭제
export const DELETE_BUILDING_REQUEST = 'DELETE_BUILDING_REQUEST';
export const DELETE_BUILDING_SUCCESS = 'DELETE_BUILDING_SUCCESS';
export const DELETE_BUILDING_FAILURE = 'DELETE_BUILDING_FAILURE';

// 대관 현황 조회
export const RENTAL_LOADING_REQUEST = 'RENTAL_LOADING_REQUEST';
export const RENTAL_LOADING_SUCCESS = 'RENTAL_LOADING_SUCCESS';
export const RENTAL_LOADING_FAILURE = 'RENTAL_LOADING_FAILURE';

// 대관 승인
export const RENTAL_ACCEPT_REQUEST = 'RENTAL_ACCEPT_REQUEST';
export const RENTAL_ACCEPT_SUCCESS = 'RENTAL_ACCEPT_SUCCESS';
export const RENTAL_ACCEPT_FAILURE = 'RENTAL_ACCEPT_FAILURE';
