// 시설물 추가
export const ADD_FACILITY_REQUEST = 'ADD_FACILITY_REQUEST';
export const ADD_FACILITY_SUCCESS = 'ADD_FACILITY_SUCCESS';
export const ADD_FACILITY_FAILURE = 'ADD_FACILITY_FAILURE';

// 시설물 변경
export const EDIT_FACILITY_REQUEST = 'EDIT_FACILITY_REQUEST';
export const EDIT_FACILITY_SUCCESS = 'EDIT_FACILITY_SUCCESS';
export const EDIT_FACILITY_FAILURE = 'EDIT_FACILITY_FAILURE';

// 시설물 삭제
export const DELETE_FACILITY_REQUEST = 'DELETE_FACILITY_REQUEST';
export const DELETE_FACILITY_SUCCESS = 'DELETE_FACILITY_SUCCESS';
export const DELETE_FACILITY_FAILURE = 'DELETE_FACILITY_FAILURE';
