// 해당 교수의 전체 연구실 정보
export const LOADING_OFFICE_REQUEST = 'LOADING_OFFICE_REQUEST';
export const LOADING_OFFICE_SUCCESS = 'LOADING_OFFICE_SUCCESS';
export const LOADING_OFFICE_FAILURE = 'LOADING_OFFICE_FAILURE';

// 추가
export const ADD_OFFICE_REQUEST = 'ADD_OFFICE_REQUEST';
export const ADD_OFFICE_SUCCESS = 'ADD_OFFICE_SUCCESS';
export const ADD_OFFICE_FAILURE = 'ADD_OFFICE_FAILURE';

// 수정(공지사항)
export const EDIT_OFFICE_REQUEST = 'EDIT_OFFICE_REQUEST';
export const EDIT_OFFICE_SUCCESS = 'EDIT_OFFICE_SUCCESS';
export const EDIT_OFFICE_FAILURE = 'EDIT_OFFICE_FAILURE';

// 삭제
export const DELETE_OFFICE_REQUEST = 'DELETE_OFFICE_REQUEST';
export const DELETE_OFFICE_SUCCESS = 'DELETE_OFFICE_SUCCESS';
export const DELETE_OFFICE_FAILURE = 'DELETE_OFFICE_FAILURE';
