// List Loading
export const PLACE_LOADING_REQUEST = 'PLACE_LOADING_REQUEST';
export const PLACE_LOADING_SUCCESS = 'PLACE_LOADING_SUCCESS';
export const PLACE_LOADING_FAILURE = 'PLACE_LOADING_FAILURE';

// Detail Loading
export const PLACE_DETAIL_LOADING_REQUEST = 'PLACE_DETAIL_LOADING_REQUEST';
export const PLACE_DETAIL_LOADING_SUCCESS = 'PLACE_DETAIL_LOADING_SUCCESS';
export const PLACE_DETAIL_LOADING_FAILURE = 'PLACE_DETAIL_LOADING_FAILURE';

// Upload
export const PLACE_UPLOAD_REQUEST = 'PLACE_UPLOAD_REQUEST';
export const PLACE_UPLOAD_SUCCESS = 'PLACE_UPLOAD_SUCCESS';
export const PLACE_UPLOAD_FAILURE = 'PLACE_UPLOAD_FAILURE';

// Edit
export const PLACE_EDIT_UPLOADING_REQUEST = 'PLACE_EDIT_UPLOADING_REQUEST';
export const PLACE_EDIT_UPLOADING_SUCCESS = 'PLACE_EDIT_UPLOADING_SUCCESS';
export const PLACE_EDIT_UPLOADING_FAILURE = 'PLACE_EDIT_UPLOADING_FAILURE';

// Delete
export const PLACE_DELETE_REQUEST = 'PLACE_DELETE_REQUEST';
export const PLACE_DELETE_SUCCESS = 'PLACE_DELETE_SUCCESS';
export const PLACE_DELETE_FAILURE = 'PLACE_DELETE_FAILURE';

// Search
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
