export const RENTAL_LIST_REQUEST = 'RENTAL_LIST_REQUEST';
export const RENTAL_LIST_SUCCESS = 'RENTAL_LIST_SUCCESS';
export const RENTAL_LIST_FAILURE = 'RENTAL_LIST_FAILURE';

export const FACILITY_DETAIL_REQUEST = 'FACILITY_DETAIL_REQUEST';
export const FACILITY_DETAIL_SUCCESS = 'FACILITY_DETAIL_SUCCESS';
export const FACILITY_DETAIL_FAILURE = 'FACILITY_DETAIL_FAILURE';

export const AVAILABLE_REQUEST = 'AVAILABLE_REQUEST';
export const AVAILABLE_SUCCESS = 'AVAILABLE_SUCCESS';
export const AVAILABLE_FAILURE = 'AVAILABLE_FAILURE';

export const RENT_REQUEST = 'RENT_REQUEST';
export const RENT_SUCCESS = 'RENT_SUCCESS';
export const RENT_FAILURE = 'RENT_FAILURE';
