// 등록
export const RESERVATION_REQUEST = 'RESERVATION_REQUEST';
export const RESERVATION_SUCCESS = 'RESERVATION_SUCCESS';
export const RESERVATION_FAILURE = 'RESERVATION_FAILURE';

// 삭제
export const DELETE_RESERVATION_REQUEST = 'DELETE_RESERVATION_REQUEST';
export const DELETE_RESERVATION_SUCCESS = 'DELETE_RESERVATION_SUCCESS';
export const DELETE_RESERVATION_FAILURE = 'DELETE_RESERVATION_FAILURE';

// 예약 가능한 건물 리스트
export const BUILDING_LIST_REQUEST = 'BUILDING_LIST_REQUEST';
export const BUILDING_LIST_SUCCESS = 'BUILDING_LIST_SUCCESS';
export const BUILDING_LIST_FAILURE = 'BUILDING_LIST_FAILURE';

// 건물 데이터
export const BUILDING_DATA_REQUEST = 'BUILDING_DATA_REQUEST';
export const BUILDING_DATA_SUCCESS = 'BUILDING_DATA_SUCCESS';
export const BUILDING_DATA_FAILURE = 'BUILDING_DATA_FAILURE';

// 건물의 층 리스트
export const FLOOR_NUM_LIST_REQUEST = 'FLOOR_NUM_LIST_REQUEST';
export const FLOOR_NUM_LIST_SUCCESS = 'FLOOR_NUM_LIST_SUCCESS';
export const FLOOR_NUM_LIST_FAILURE = 'FLOOR_NUM_LIST_FAILURE';

// 건물 해당 층의 강의실 리스트
export const FLOOR_LIST_REQUEST = 'FLOOR_LIST_REQUEST';
export const FLOOR_LIST_SUCCESS = 'FLOOR_LIST_SUCCESS';
export const FLOOR_LIST_FAILURE = 'FLOOR_LIST_FAILURE';

// 건물 이미지
export const BUILDING_IMAGE_REQUEST = 'BUILDING_IMAGE_REQUEST';
export const BUILDING_IMAGE_SUCCESS = 'BUILDING_IMAGE_SUCCESS';
export const BUILDING_IMAGE_FAILURE = 'BUILDING_IMAGE_FAILURE';

// 강의실 예약 가능 시간
export const RESERVATION_TIME_REQUEST = 'RESERVATION_TIME_REQUEST';
export const RESERVATION_TIME_SUCCESS = 'RESERVATION_TIME_SUCCESS';
export const RESERVATION_TIME_FAILURE = 'RESERVATION_TIME_FAILURE';
