// 스케줄 리스트
export const SCHEDULE_LIST_REQUEST = 'SCHEDULE_LIST_REQUEST';
export const SCHEDULE_LIST_SUCCESS = 'SCHEDULE_LIST_SUCCESS';
export const SCHEDULE_LIST_FAILURE = 'SCHEDULE_LIST_FAILURE';

export const SCHEDULE_REQUEST = 'SCHEDULE_REQUEST';
export const SCHEDULE_SUCCESS = 'SCHEDULE_SUCCESS';
export const SCHEDULE_FAILURE = 'SCHEDULE_FAILURE';

// 스케줄 추가
export const SCHEDULE_ADD_REQUEST = 'SCHEDULE_ADD_REQUEST';
export const SCHEDULE_ADD_SUCCESS = 'SCHEDULE_ADD_SUCCESS';
export const SCHEDULE_ADD_FAILURE = 'SCHEDULE_ADD_FAILURE';

// 스케줄 삭제
export const SCHEDULE_DELETE_REQUEST = 'SCHEDULE_DELETE_REQUEST';
export const SCHEDULE_DELETE_SUCCESS = 'SCHEDULE_DELETE_SUCCESS';
export const SCHEDULE_DELETE_FAILURE = 'SCHEDULE_DELETE_FAILURE';

// now schedule
export const SCHEDULE_NOW_REQUEST = 'SCHEDULE_NOW_REQUEST';
export const SCHEDULE_NOW_SUCCESS = 'SCHEDULE_NOW_SUCCESS';
export const SCHEDULE_NOW_FAILURE = 'SCHEDULE_NOW_FAILURE';

// next schedule
export const SCHEDULE_NEXT_REQUEST = 'SCHEDULE_NEXT_REQUEST';
export const SCHEDULE_NEXT_SUCCESS = 'SCHEDULE_NEXT_SUCCESS';
export const SCHEDULE_NEXT_FAILURE = 'SCHEDULE_NEXT_FAILURE';

// Search Subject
export const SEARCH_SUBJECT_REQUEST = 'SEARCH_SUBJECT_REQUEST';
export const SEARCH_SUBJECT_SUCCESS = 'SEARCH_SUBJECT_SUCCESS';
export const SEARCH_SUBJECT_FAILURE = 'SEARCH_SUBJECT_FAILURE';

// 공지
export const NOTICE_REQUEST = 'NOTICE_REQUEST';
export const NOTICE_SUCCESS = 'NOTICE_SUCCESS';
export const NOTICE_FAILURE = 'NOTICE_FAILURE';
