// 스케줄 리스트
export const SCHEDULE_LIST_REQUEST = 'SCHEDULE_LIST_REQUEST';
export const SCHEDULE_LIST_SUCCESS = 'SCHEDULE_LIST_SUCCESS';
export const SCHEDULE_LIST_FAILURE = 'SCHEDULE_LIST_FAILURE';

// 스케줄 삭제
export const SCHEDULE_DELETE_REQUEST = 'SCHEDULE_DELETE_REQUEST';
export const SCHEDULE_DELETE_SUCCESS = 'SCHEDULE_DELETE_SUCCESS';
export const SCHEDULE_DELETE_FAILURE = 'SCHEDULE_DELETE_FAILURE';
