// LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// GOOGLE LOGIN
export const GOOGLE_LOGIN_REQUEST = 'GOOGLE_LOGIN_REQUEST';
export const GOOGLE_LOGIN_SUCCESS = 'GOOGLE_LOGIN_SUCCESS';
export const GOOGLE_LOGIN_FAILURE = 'GOOGLE_LOGIN_FAILURE';

// LOGOUT
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// REGISTER
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// USER LOADING
export const USER_LOADING_REQUEST = 'USER_LOADING_REQUEST';
export const USER_LOADING_SUCCESS = 'USER_LOADING_SUCCESS';
export const USER_LOADING_FAILURE = 'USER_LOADING_FAILURE';

// CHANGE PASSWORD
export const USER_EMAIL_AUTH_REQUEST = 'USER_EMAIL_AUTH_REQUEST';
export const USER_EMAIL_AUTH_SUCCESS = 'USER_EMAIL_AUTH_SUCCESS';
export const USER_EMAIL_AUTH_FAILURE = 'USER_EMAIL_AUTH_FAILURE';

// 문자 전송
export const SEND_REQUEST = 'SEND_REQUEST';
export const SEND_SUCCESS = 'SEND_SUCCESS';
export const SEND_FAILURE = 'SEND_FAILURE';

// 인증번호 인증
export const AUTH_NUM_REQUEST = 'AUTH_NUM_REQUEST';
export const AUTH_NUM_SUCCESS = 'AUTH_NUM_SUCCESS';
export const AUTH_NUM_FAILURE = 'AUTH_NUM_FAILURE';
